name: movie_sphere
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.10
  google_fonts: ^6.2.1
  get: ^4.6.6
  shared_preferences: ^2.3.4
  device_preview: ^1.2.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  flutter_svg: ^2.0.16
  dots_indicator: ^3.0.0
  animate_do: ^3.1.2
  pinput: ^5.0.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  mobile_scanner: ^6.0.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_advanced_switch: ^3.1.0
  flutter_launcher_icons: ^0.14.2
  persistent_bottom_nav_bar: ^6.2.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  share_plus: ^10.1.3
  http: ^1.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  image_path: "assets/images/app_logo.png"
  min_sdk_version: 21
